version: "3.0"
services:
    backend:
        build:
            context: ./backend
        container_name: "ecommerce_backend"
        depends_on:
            - mongo
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - ./backend:/app
        environment: 
            - MONGODB_URI=mongodb://mongo:27017/ecommerce
            - PORT=3000

    mongo: 
        image: mongo:4.4.4-bionic
        container_name: "ecommerce_mongo"
        ports:
            - 27017:27017
        volumes:
            - ./backend/data:/data